server {
    listen 80;
    server_name nebulaeventos.ddns.net 100.49.147.27;

    # Tamaño máximo para uploads (imágenes de eventos, etc.)
    client_max_body_size 20M;

    # Logs
    access_log /var/log/nginx/nebula-access.log;
    error_log  /var/log/nginx/nebula-error.log;

    root /home/ubuntu/nebulaupgrade/public;

    location / {
        proxy_pass         http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        'upgrade';
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 60s;
    }
}
